### ISSUE TITLE
What are the benefits of using an intermediate server mvstore with Foundationdb?

### ISSUE THREAD

**Issue by harryfei** [losfair/mvsqlite#111]
What's the role and benefits of mvstore server?

Is it possible to make mvsqlite client side library connect to Foundation db cluster directly?

**Comment by losfair** [comment]
`mvstore` is the middleware service to ensure multi-tenant isolation and security. It exposes two ports:

- Data plane API (default port 7000)
- Admin API (default port 7001)

The data plane API is what the client library connects to, and is safe to expose to the internet. Clients are considered untrusted and should not be able to access other tenants' data in the same cluster or break data structure invariants. These constraints are enforced by `mvstore`.
